
import "./globals.css";

export const metadata = {
  title: "Dawin tours and travel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="h-full"
      >
        
      
          {children}
       
      </body>
    </html>
  );
}
